name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Statrting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm i
      - name: unit test
        run: npm run test:unit
      - name: build prj
        run: npm run build
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v4
      - name: docs
        if: contains(github.ref, 'release')
        run: ./doxygen /home/alex/WebstormProjects/ci-cd/doxyfile

  selenium:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - name: Statrting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: selenium cd
        run: cd seleniumtest
      - name: installing selenium
        run: npm i selenium-webdriver
      - name: testing
        run: node seleniumTest.js